const I18N = {
  en: {
    hero:{eyebrow:'ACTIVE BETA · COMMERCIAL REAL ESTATE OFF-MARKET',title:'Present with rigour.<br><em>Connect with judgement.</em>',lede:'Turn scattered information about an asset into an auditable institutional teaser — then connect it, anonymously, with acquisition mandates that fit.',primary:'Structure an asset <span>↗</span>',secondary:'Activate my radar <span>→</span>',traceTitle:'Complete traceability',traceBody:'Every teaser datum is linked back to its source.',mandateLabel:'ACQUISITION MANDATE',mandateTitle:'Urban hotel · core / core+'},
    assurance:{browser:'Read in-browser',zero:'Zero fabrication',provenance:'Cell-by-cell provenance',blind:'Double-blind matching'},
    status:{verified:'Verified',review:'Review'},
    proof:{oneTitle:'Institutional teasers',oneBody:'Ready for the investment committee',twoTitle:'Traceable intelligence',twoBody:'Auditable from source to output',threeTitle:'Anonymous connection',threeBody:'Double-blind before identity'},
    statement:{kicker:'THE MARKET PROBLEM',title:'The asset may be real.<br><em>The signal is still scattered.</em>',body:'An IM, PDF files, a financial model, broker notes, images, emails and conversations. Before an opportunity can be presented with confidence, someone has to bring the evidence together, check every figure and decide what the other side is allowed to see.',punch:'The problem is not a lack of information. It is a lack of structure, traceability and fit.'},
    walkthrough:{kicker:'THE LOPTOR METHOD',title:'From scattered files<br><em>to a defensible teaser.</em>',intro:'See how an opportunity moves from a messy file set to an institutional presentation without losing the relationship between a claim and its source.',demoLabel:'FICTIONAL WORKSPACE · NO PRODUCTION DATA'},
    seller:{kicker:'FOR THE SELL-SIDE',title:'Present the asset<br><em>without overexposing it.</em>',body:'A good teaser is not the one that says the most. It is the one that shows enough to create interest while keeping control of what remains to be verified or requested.',feature1Title:'The living dossier',feature1Body:'Keep the asset’s sources, coverage and evolution together.',feature2Title:'Selective visibility',feature2Body:'Issue a text-only, one-photo or gallery teaser.',feature3Title:'Anonymity checks',feature3Body:'Flag signs that could reveal the asset too early.',cta:'Structure an asset <span>↗</span>'},
    buyer:{kicker:'FOR THE BUY-SIDE',title:'Let your mandate<br><em>work quietly.</em>',body:'Define what you are looking for, where, at what ticket and with which exclusions. LoptorCRE watches the market in the background and alerts you when a fit appears.',punch:'You do not need a catalogue of assets. You need the opportunities that meet your mandate.',cta:'Activate passive radar <span>→</span>'},
    darkpool:{kicker:'THE DARK POOL',title:'The liquidity that<br><em>doesn’t appear in a catalogue.</em>',body:'Some assets should not be published. Some buyers do not want to announce themselves. LoptorCRE creates the point of connection without sacrificing the confidentiality of the process.',principle:'Fit first. Identity later.',lock:'Identity protected until consent'},
    portfolio:{kicker:'FOR THE WHOLE PORTFOLIO',title:'From one asset<br><em>to a clearer portfolio.</em>',body:'When opportunities multiply, you need to know what is documented, what is ready to present and where new connections are forming.'},
    trust:{kicker:'RADICAL TRANSPARENCY',title:'Built to structure and connect.<br><em>Not to promise everything.</em>',intro:'Trust also means explaining the limits of the product.',yesTitle:'LoptorCRE is',yes1:'An analytical structuring engine for scattered documents.',yes2:'An institutional A4 teaser generator with selective visibility.',yes3:'An anonymous matching layer for financial and operational parameters.',yes4:'A documentary certainty audit with zero fabrication.',noTitle:'LoptorCRE is not',no1:'A VDR for storing a complete due diligence.',no2:'A service for NDAs or electronic signatures.',no3:'An open commercial catalogue of assets or buyers.',no4:'A place to share full files before consent.'},
    pricing:{kicker:'PRICING BY TEAM SIZE',title:'Start at the level<br><em>you need today.</em>',intro:'From an independent broker to a transaction team or fund, LoptorCRE grows with the assets, users and mandates you coordinate.',recommended:'MOST USED',soloName:'Independent broker',soloDesc:'Structure assets with individual control.',boutiqueName:'Transactional teams',boutiqueDesc:'Coordinate operations, people and brand.',fundsName:'Institutional scale',fundsDesc:'Coordinate portfolios and mandates at scale.',cta:'Choose plan <span>↗</span>',buyerTitle:'For buyers: passive radar is free.',buyerBody:'Register mandates and receive anonymous alerts. Unlock contacts only when there is a fit.',buyerCta:'Activate radar <span>→</span>'},
    beta:{kicker:'THE BETA',title:'The beta starts with<br><em>what matters most.</em>',body:'The first version focuses on structuring dossiers, controlling visibility, issuing institutional teasers and finding anonymous fits. Collaboration and secure sharing will expand progressively.',cta:'Read the product boundaries <span>↓</span>',liveLabel:'LIVE IN BETA',liveTitle:'Evidence-led foundation',live1:'Provenance and conflicts',live2:'Three teaser visibility levels',live3:'Mandates, Dark Pool and portfolio overview',live4:'Bilingual ES / EN experience',nextLabel:'IN DEVELOPMENT',nextTitle:'Secure collaboration',next1:'Secure sharing link',next2:'Deal Rooms',next3:'Meeting mode and operation roles',next4:'French experience'},
    faq:{kicker:'FAQ',title:'Precision before<br><em>persuasion.</em>',intro:'A few direct answers for teams evaluating LoptorCRE'},
    final:{eyebrow:'OFF-MARKET CRE INTELLIGENCE',title:'Make every asset<br><em>ready for the right table.</em>',body:'Structure the evidence. Protect the confidentiality. Find the fit.',primary:'Structure an asset <span>↗</span>',secondary:'Activate my radar <span>→</span>'},
    nav:{how:'How it works',sell:'For sellers',buy:'For buyers',pricing:'Pricing',access:'Access platform <span>↗</span>'},
    steps:[{title:'Bring the evidence',short:'Start where the information already lives.',description:'Bring an IM, spreadsheet, broker note or message thread. The information starts where you already keep it.'},{title:'Keep the provenance',short:'Every number carries its trail.',description:'Each proposed figure keeps an explicit reference: document, page or cell. A number never appears alone.'},{title:'Surface conflicts',short:'A disagreement stays visible.',description:'When two sources disagree, LoptorCRE does not choose for you or fill the gap. The datum stays under review.'},{title:'Choose visibility',short:'You decide what the market sees.',description:'Select what the investor can see. An unconfirmed datum does not become an ambiguous gap — it simply stays out.'},{title:'Issue the teaser',short:'A4, institutional, ready to share.',description:'Generate an institutional A4 teaser with the right level of exposure: text only, one photo or gallery.'},{title:'Match anonymously',short:'Fit first. Identity later.',description:'The asset can enter a blind match with structured acquisition mandates. Identity comes only after both sides consent.'}],
    faqItems:[['What does LoptorCRE do?','LoptorCRE structures scattered asset information into auditable institutional teasers and anonymously matches those assets with acquisition mandates.'],['Does LoptorCRE invent or complete missing data?','No. If a datum is not present in the sources, it does not exist in the teaser. Conflicts remain visible and unresolved figures are not printed.'],['Is LoptorCRE a VDR or a public listing portal?','No. It is not a VDR for heavy due diligence and it is not an open catalogue. It is a structuring, visibility-control and anonymous matching layer.'],['When are identities revealed?','Only after both parties have reviewed the blind profile and explicitly consented to contact.'],['Can buyers use LoptorCRE for free?','The passive radar is free for registering acquisition mandates and receiving anonymous alerts. Contact-unlock options are available for active buyer teams.'],['Where is the application?','The product workspace is separate from this public landing and is available at app.loptorcre.com.']]
  },
  es: {
    hero:{eyebrow:'BETA ACTIVA · COMMERCIAL REAL ESTATE OFF-MARKET',title:'Presenta con rigor.<br><em>Conecta con criterio.</em>',lede:'Convierte la información dispersa de un activo en un teaser institucional auditable y crúzalo, de forma anónima, con mandatos de compra que encajan.',primary:'Estructurar un activo <span>↗</span>',secondary:'Activar mi radar <span>→</span>',traceTitle:'Trazabilidad completa',traceBody:'Cada dato del teaser está vinculado a su fuente.',mandateLabel:'MANDATO DE COMPRA',mandateTitle:'Hotel urbano · core / core+'},
    assurance:{browser:'Lectura en navegador',zero:'Cero fabricación',provenance:'Procedencia celda a celda',blind:'Cruce doble ciego'},
    status:{verified:'Verificado',review:'Revisar'},
    proof:{oneTitle:'Teasers institucionales',oneBody:'Listos para el comité de inversión',twoTitle:'Inteligencia trazable',twoBody:'Auditable desde la fuente al resultado',threeTitle:'Conexión anónima',threeBody:'Doble ciego antes de la identidad'},
    statement:{kicker:'EL PROBLEMA DEL MERCADO',title:'El activo puede ser real.<br><em>La señal sigue dispersa.</em>',body:'Un IM, PDFs, un modelo financiero, notas del broker, imágenes, correos y conversaciones. Antes de presentar una oportunidad con confianza, alguien tiene que reunir la evidencia, comprobar cada cifra y decidir qué puede ver la otra parte.',punch:'El problema no es la falta de información. Es la falta de estructura, trazabilidad y encaje.'},
    walkthrough:{kicker:'EL MÉTODO LOPTOR',title:'Del expediente disperso<br><em>a un teaser defendible.</em>',intro:'Mira cómo una oportunidad pasa de un conjunto desordenado de documentos a una presentación institucional sin perder la relación entre cada afirmación y su fuente.',demoLabel:'ESPACIO FICTICIO · SIN DATOS DE PRODUCCIÓN'},
    seller:{kicker:'PARA QUIEN VENDE',title:'Presenta el activo<br><em>sin sobreexponerlo.</em>',body:'Un buen teaser no es el que dice más. Es el que muestra lo suficiente para despertar interés y mantiene el control sobre lo que queda por verificar o solicitar.',feature1Title:'El expediente vivo',feature1Body:'Conserva juntas las fuentes, la cobertura y la evolución del activo.',feature2Title:'Visibilidad selectiva',feature2Body:'Emite un teaser solo texto, con una foto o con galería.',feature3Title:'Controles de anonimato',feature3Body:'Detecta señales que podrían revelar el activo demasiado pronto.',cta:'Estructurar un activo <span>↗</span>'},
    buyer:{kicker:'PARA QUIEN COMPRA',title:'Deja que tu mandato<br><em>trabaje en silencio.</em>',body:'Define qué buscas, dónde, con qué ticket y qué exclusiones aplican. LoptorCRE vigila el mercado en segundo plano y te avisa cuando aparece un encaje.',punch:'No necesitas un catálogo de activos. Necesitas las oportunidades que cumplen tu mandato.',cta:'Activar radar pasivo <span>→</span>'},
    darkpool:{kicker:'EL DARK POOL',title:'La liquidez que<br><em>no aparece en un catálogo.</em>',body:'Hay activos que no deben publicarse y compradores que no quieren anunciarse. LoptorCRE crea el punto de conexión sin sacrificar la confidencialidad del proceso.',principle:'Primero el encaje. Después la identidad.',lock:'Identidad protegida hasta el consentimiento'},
    portfolio:{kicker:'PARA TODA LA CARTERA',title:'Del activo individual<br><em>a una cartera más clara.</em>',body:'Cuando las oportunidades se multiplican, necesitas saber qué está documentado, qué está listo para presentar y dónde se están formando nuevas conexiones.'},
    trust:{kicker:'TRANSPARENCIA RADICAL',title:'Diseñada para estructurar y conectar.<br><em>No para prometerlo todo.</em>',intro:'La confianza también consiste en explicar los límites del producto.',yesTitle:'LoptorCRE sí es',yes1:'Un motor de estructuración analítica para documentos dispersos.',yes2:'Un generador de teasers A4 institucionales con visibilidad selectiva.',yes3:'Una capa de matching anónimo por parámetros financieros y operativos.',yes4:'Un auditor de certeza documental con cero fabricación.',noTitle:'LoptorCRE no es',no1:'Un VDR para almacenar una due diligence completa.',no2:'Un servicio para NDAs o firmas electrónicas.',no3:'Un catálogo comercial abierto de activos o compradores.',no4:'Un lugar para compartir archivos completos antes del consentimiento.'},
    pricing:{kicker:'PRECIOS POR TAMAÑO DE EQUIPO',title:'Empieza con el nivel<br><em>que necesitas hoy.</em>',intro:'Desde un broker independiente hasta un equipo transaccional o un fondo, LoptorCRE crece con los activos, usuarios y mandatos que coordinas.',recommended:'MÁS UTILIZADO',soloName:'Broker independiente',soloDesc:'Estructura activos con control individual.',boutiqueName:'Equipos transaccionales',boutiqueDesc:'Coordina operaciones, personas y marca.',fundsName:'Escala institucional',fundsDesc:'Coordina carteras y mandatos a escala.',cta:'Elegir plan <span>↗</span>',buyerTitle:'Para compradores: el radar pasivo es gratuito.',buyerBody:'Registra mandatos y recibe alertas anónimas. Desbloquea contactos solo cuando exista encaje.',buyerCta:'Activar radar <span>→</span>'},
    beta:{kicker:'LA BETA',title:'La beta empieza por<br><em>lo que más importa.</em>',body:'La primera versión se centra en estructurar expedientes, controlar la visibilidad, emitir teasers institucionales y encontrar encajes anónimos. La colaboración y el intercambio seguro crecerán progresivamente.',cta:'Leer los límites del producto <span>↓</span>',liveLabel:'DISPONIBLE EN BETA',liveTitle:'Base guiada por evidencia',live1:'Procedencia y conflictos',live2:'Tres niveles de visibilidad del teaser',live3:'Mandatos, Dark Pool y resumen de cartera',live4:'Experiencia bilingüe ES / EN',nextLabel:'EN DESARROLLO',nextTitle:'Colaboración segura',next1:'Enlace seguro de compartir',next2:'Deal Rooms',next3:'Modo reunión y roles en la operación',next4:'Experiencia en francés'},
    faq:{kicker:'FAQ',title:'Precisión antes<br><em>que persuasión.</em>',intro:'Respuestas directas para equipos que están evaluando LoptorCRE.'},
    final:{eyebrow:'INTELIGENCIA CRE OFF-MARKET',title:'Haz que cada activo<br><em>llegue a la mesa adecuada.</em>',body:'Estructura la evidencia. Protege la confidencialidad. Encuentra el encaje.',primary:'Estructurar un activo <span>↗</span>',secondary:'Activar mi radar <span>→</span>'},
    nav:{how:'Cómo funciona',sell:'Para quien vende',buy:'Para quien compra',pricing:'Precios',access:'Acceder a la plataforma <span>↗</span>'},
    steps:[{title:'Trae la evidencia',short:'Empieza donde ya vive la información.',description:'Trae un IM, un Excel, una nota del broker o un hilo de mensajes. La información empieza donde ya la tienes.'},{title:'Conserva la procedencia',short:'Cada cifra lleva su rastro.',description:'Cada cifra propuesta conserva una referencia explícita: documento, página o celda. Un número nunca aparece solo.'},{title:'Haz visibles los conflictos',short:'Una discrepancia permanece visible.',description:'Cuando dos fuentes discrepan, LoptorCRE no elige por ti ni rellena el vacío. El dato queda en verificación.'},{title:'Decide la visibilidad',short:'Tú decides qué ve el mercado.',description:'Selecciona qué puede ver el inversor. Un dato no confirmado no se convierte en un hueco ambiguo: simplemente queda fuera.'},{title:'Emite el teaser',short:'A4, institucional, listo para compartir.',description:'Genera un teaser A4 institucional con el nivel de exposición adecuado: solo texto, una foto o galería.'},{title:'Cruza de forma anónima',short:'Primero el encaje. Después la identidad.',description:'El activo puede entrar en un cruce ciego con mandatos de compra estructurados. La identidad solo llega tras el consentimiento de ambas partes.'}],
    faqItems:[['¿Qué hace LoptorCRE?','LoptorCRE estructura información dispersa de activos en teasers institucionales auditables y cruza esos activos de forma anónima con mandatos de compra.'],['¿LoptorCRE inventa o completa datos que faltan?','No. Si un dato no aparece en las fuentes, no existe en el teaser. Los conflictos permanecen visibles y las cifras no resueltas no se imprimen.'],['¿Es LoptorCRE un VDR o un portal público de activos?','No. No es un VDR para una due diligence pesada ni un catálogo abierto. Es una capa de estructuración, control de visibilidad y matching anónimo.'],['¿Cuándo se revelan las identidades?','Solo después de que ambas partes hayan revisado la ficha ciega y consientan expresamente el contacto.'],['¿Pueden utilizar LoptorCRE los compradores de forma gratuita?','El radar pasivo es gratuito para registrar mandatos y recibir alertas anónimas. Hay opciones de desbloqueo para equipos compradores activos.'],['¿Dónde está la aplicación?','El espacio de trabajo del producto está separado de esta landing pública y se encuentra en app.loptorcre.com.']]
  },
  fr: {
    hero:{eyebrow:'BÊTA ACTIVE · COMMERCIAL REAL ESTATE OFF-MARKET',title:'Présentez avec rigueur.<br><em>Connectez avec discernement.</em>',lede:'Transformez les informations dispersées d’un actif en teaser institutionnel auditable, puis mettez-le en relation, de façon anonyme, avec les mandats d’acquisition pertinents.',primary:'Structurer un actif <span>↗</span>',secondary:'Activer mon radar <span>→</span>',traceTitle:'Traçabilité complète',traceBody:'Chaque donnée du teaser est reliée à sa source.',mandateLabel:'MANDAT D’ACQUISITION',mandateTitle:'Hôtel urbain · core / core+'},
    assurance:{browser:'Lecture dans le navigateur',zero:'Zéro fabrication',provenance:'Provenance cellule par cellule',blind:'Matching en double aveugle'},
    status:{verified:'Vérifié',review:'À vérifier'},
    proof:{oneTitle:'Teasers institutionnels',oneBody:'Prêts pour le comité d’investissement',twoTitle:'Intelligence traçable',twoBody:'Auditable de la source au résultat',threeTitle:'Connexion anonyme',threeBody:'Double aveugle avant l’identité'},
    statement:{kicker:'LE PROBLÈME DU MARCHÉ',title:'L’actif peut être réel.<br><em>Le signal reste dispersé.</em>',body:'Un IM, des PDF, un modèle financier, des notes de broker, des images, des e-mails et des conversations. Avant de présenter une opportunité avec confiance, il faut rassembler les preuves, vérifier chaque chiffre et décider ce que l’autre partie peut voir.',punch:'Le problème n’est pas le manque d’informations. C’est le manque de structure, de traçabilité et d’adéquation.'},
    walkthrough:{kicker:'LA MÉTHODE LOPTOR',title:'Des fichiers dispersés<br><em>au teaser défendable.</em>',intro:'Voyez comment une opportunité passe d’un ensemble de documents désordonné à une présentation institutionnelle sans perdre le lien entre chaque affirmation et sa source.',demoLabel:'ESPACE FICTIF · AUCUNE DONNÉE DE PRODUCTION'},
    seller:{kicker:'POUR LES VENDEURS',title:'Présentez l’actif<br><em>sans le surexposer.</em>',body:'Un bon teaser n’est pas celui qui en dit le plus. C’est celui qui montre assez pour susciter l’intérêt tout en gardant le contrôle de ce qui reste à vérifier ou à demander.',feature1Title:'Le dossier vivant',feature1Body:'Conservez les sources, la couverture et l’évolution de l’actif.',feature2Title:'Visibilité sélective',feature2Body:'Émettez un teaser texte seul, une photo ou une galerie.',feature3Title:'Contrôles d’anonymat',feature3Body:'Signalez les indices qui pourraient révéler l’actif trop tôt.',cta:'Structurer un actif <span>↗</span>'},
    buyer:{kicker:'POUR LES ACHETEURS',title:'Laissez votre mandat<br><em>travailler discrètement.</em>',body:'Définissez ce que vous recherchez, où, pour quel ticket et avec quelles exclusions. LoptorCRE surveille le marché en arrière-plan et vous alerte lorsqu’une adéquation apparaît.',punch:'Vous n’avez pas besoin d’un catalogue d’actifs. Vous avez besoin des opportunités qui correspondent à votre mandat.',cta:'Activer le radar passif <span>→</span>'},
    darkpool:{kicker:'LE DARK POOL',title:'La liquidité qui<br><em>n’apparaît dans aucun catalogue.</em>',body:'Certains actifs ne doivent pas être publiés. Certains acheteurs ne veulent pas s’annoncer. LoptorCRE crée le point de rencontre sans sacrifier la confidentialité du processus.',principle:'L’adéquation d’abord. L’identité ensuite.',lock:'Identité protégée jusqu’au consentement'},
    portfolio:{kicker:'POUR TOUT LE PORTEFEUILLE',title:'D’un actif<br><em>à un portefeuille plus lisible.</em>',body:'Lorsque les opportunités se multiplient, vous devez savoir ce qui est documenté, ce qui est prêt à être présenté et où de nouvelles connexions se forment.'},
    trust:{kicker:'TRANSPARENCE RADICALE',title:'Conçue pour structurer et connecter.<br><em>Pas pour tout promettre.</em>',intro:'La confiance consiste aussi à expliquer les limites du produit.',yesTitle:'LoptorCRE est',yes1:'Un moteur de structuration analytique pour les documents dispersés.',yes2:'Un générateur de teasers A4 institutionnels à visibilité sélective.',yes3:'Une couche de matching anonyme par paramètres financiers et opérationnels.',yes4:'Un audit de certitude documentaire sans fabrication.',noTitle:'LoptorCRE n’est pas',no1:'Un VDR pour stocker une due diligence complète.',no2:'Un service de NDA ou de signature électronique.',no3:'Un catalogue commercial ouvert d’actifs ou d’acheteurs.',no4:'Un espace de partage de fichiers complets avant consentement.'},
    pricing:{kicker:'TARIFS PAR TAILLE D’ÉQUIPE',title:'Commencez au niveau<br><em>dont vous avez besoin.</em>',intro:'Du broker indépendant au fonds ou à l’équipe transactionnelle, LoptorCRE évolue avec les actifs, utilisateurs et mandats que vous coordonnez.',recommended:'LE PLUS CHOISI',soloName:'Broker indépendant',soloDesc:'Structurez vos actifs avec un contrôle individuel.',boutiqueName:'Équipes transactionnelles',boutiqueDesc:'Coordonnez opérations, équipes et marque.',fundsName:'Échelle institutionnelle',fundsDesc:'Coordonnez portefeuilles et mandats à grande échelle.',cta:'Choisir le plan <span>↗</span>',buyerTitle:'Pour les acheteurs : le radar passif est gratuit.',buyerBody:'Enregistrez vos mandats et recevez des alertes anonymes. Débloquez les contacts lorsqu’une adéquation existe.',buyerCta:'Activer le radar <span>→</span>'},
    beta:{kicker:'LA BÊTA',title:'La bêta commence par<br><em>l’essentiel.</em>',body:'La première version se concentre sur la structuration des dossiers, le contrôle de la visibilité, l’émission de teasers institutionnels et la recherche d’adéquations anonymes. La collaboration et le partage sécurisé évolueront progressivement.',cta:'Lire les limites du produit <span>↓</span>',liveLabel:'DISPONIBLE EN BÊTA',liveTitle:'Fondation guidée par les preuves',live1:'Provenance et conflits',live2:'Trois niveaux de visibilité du teaser',live3:'Mandats, Dark Pool et vue portefeuille',live4:'Expérience bilingue ES / EN',nextLabel:'EN DÉVELOPPEMENT',nextTitle:'Collaboration sécurisée',next1:'Lien de partage sécurisé',next2:'Deal Rooms',next3:'Mode réunion et rôles dans l’opération',next4:'Expérience française'},
    faq:{kicker:'FAQ',title:'La précision avant<br><em>la persuasion.</em>',intro:'Des réponses directes pour les équipes qui évaluent LoptorCRE.'},
    final:{eyebrow:'INTELLIGENCE CRE OFF-MARKET',title:'Faites en sorte que chaque actif<br><em>arrive à la bonne table.</em>',body:'Structurez les preuves. Protégez la confidentialité. Trouvez l’adéquation.',primary:'Structurer un actif <span>↗</span>',secondary:'Activer mon radar <span>→</span>'},
    nav:{how:'Comment ça marche',sell:'Pour les vendeurs',buy:'Pour les acheteurs',pricing:'Tarifs',access:'Accéder à la plateforme <span>↗</span>'},
    steps:[{title:'Apportez les preuves',short:'Commencez là où se trouve l’information.',description:'Apportez un IM, un tableur, une note de broker ou un fil de messages. L’information commence là où vous la conservez déjà.'},{title:'Conservez la provenance',short:'Chaque chiffre garde sa trace.',description:'Chaque chiffre proposé conserve une référence explicite : document, page ou cellule. Un chiffre n’apparaît jamais seul.'},{title:'Rendez les conflits visibles',short:'Un désaccord reste visible.',description:'Lorsque deux sources divergent, LoptorCRE ne choisit pas à votre place et ne comble pas le vide. La donnée reste à vérifier.'},{title:'Choisissez la visibilité',short:'Vous décidez ce que voit le marché.',description:'Sélectionnez ce que l’investisseur peut voir. Une donnée non confirmée ne devient pas un vide ambigu : elle reste simplement hors du teaser.'},{title:'Émettez le teaser',short:'A4, institutionnel, prêt à partager.',description:'Générez un teaser A4 institutionnel avec le bon niveau d’exposition : texte seul, une photo ou une galerie.'},{title:'Matchez anonymement',short:'L’adéquation d’abord. L’identité ensuite.',description:'L’actif peut entrer dans un matching aveugle avec des mandats d’acquisition structurés. L’identité n’arrive qu’après le consentement des deux parties.'}],
    faqItems:[['Que fait LoptorCRE ?','LoptorCRE structure les informations dispersées d’un actif en teasers institutionnels auditables et met anonymement ces actifs en relation avec des mandats d’acquisition.'],['LoptorCRE invente-t-il ou complète-t-il les données manquantes ?','Non. Si une donnée ne figure pas dans les sources, elle n’existe pas dans le teaser. Les conflits restent visibles et les chiffres non résolus ne sont pas imprimés.'],['LoptorCRE est-il un VDR ou un portail public d’annonces ?','Non. Ce n’est ni un VDR pour une due diligence lourde, ni un catalogue ouvert. C’est une couche de structuration, de contrôle de visibilité et de matching anonyme.'],['Quand les identités sont-elles révélées ?','Uniquement après que les deux parties ont consulté le profil aveugle et consenti explicitement au contact.'],['Les acheteurs peuvent-ils utiliser LoptorCRE gratuitement ?','Le radar passif est gratuit pour enregistrer des mandats et recevoir des alertes anonymes. Des options de déblocage existent pour les équipes d’achat actives.'],['Où se trouve l’application ?','L’espace de travail est séparé de cette landing publique et se trouve sur app.loptorcre.com.']]
  }
};

const demoTemplates = [
  `<div class="demo-files"><div class="demo-file is-uploading"><span class="file-icon">PDF</span><div><b>asset_information.pdf</b><small>24 pages · 6.4 MB · reading in browser</small></div><span class="status status-verified"><i></i></span></div><div class="demo-file"><span class="file-icon">XLS</span><div><b>operating_model.xlsx</b><small>12 sheets · 1.2 MB</small></div></div><div class="demo-file"><span class="file-icon">TXT</span><div><b>broker_notes.txt</b><small>3.1 KB · pasted note</small></div></div><div class="demo-upload"><span class="upload-plus">+</span><div><b>Drop more evidence</b><small>PDF · XLSX · DOCX · notes</small></div></div></div>`,
  `<div class="demo-proof"><div class="proof-source-card"><label><span>ASSET INFORMATION.PDF</span><b>VERIFIED</b></label><div class="proof-data">€42.8M <small>ASKING PRICE</small></div></div><div class="proof-source-card"><label><span>OPERATING_MODEL.XLSX</span><b>VERIFIED</b></label><div class="proof-data">6.4% <small>STABILIZED YIELD</small></div></div><div class="proof-cite"><span class="cite-mark">⌁</span><span>Each figure retains its source reference: <b>PDF · p. 03 · paragraph 4</b> and <b>XLSX · sheet Returns · cell D8</b>.</span></div></div>`,
  `<div class="conflict-card"><div class="conflict-head"><span>DOCUMENT CONFLICT · HOTEL_KEYS</span><span>UNDER REVIEW</span></div><div class="conflict-rows"><div class="conflict-row"><span>Asset information.pdf</span><strong>128</strong><em>Page 7</em></div><div class="conflict-row"><span>Broker notes.txt</span><strong>132</strong><em>Note 02</em></div><div class="conflict-row"><span>Output status</span><strong>—</strong><em>Not printed</em></div></div></div>`,
  `<div class="visibility-demo"><div class="visibility-card is-selected"><span>LEVEL 01</span><h4>Text only</h4><p>Financial ratios and technical narrative. Most restrictive and confidential.</p></div><div class="visibility-card"><span>LEVEL 02</span><h4>One photo</h4><p>One anonymous image or audited architectural plan.</p></div><div class="visibility-card"><span>LEVEL 03</span><h4>Gallery</h4><p>Multiple images without brands or urban landmarks.</p></div></div>`,
  `<div class="a4-demo"><div class="a4-sheet"><div class="sheet-meta"><span>CONFIDENTIAL</span><span>A4 TEASER</span></div><h4>Urban hotel<br><em>prime location</em></h4><p>Barcelona · Spain</p><div class="a4-cover"></div><div class="a4-lines"></div></div><div class="a4-side"><b>READY TO SHARE</b><span>Every printed datum has a source. Every hidden datum stays hidden.</span></div></div>`,
  `<div class="match-demo"><div class="match-box"><small>ANONYMOUS ASSET</small><b>Urban hotel</b><p>Barcelona · €42.8M · 6.4% yield</p></div><div class="match-mid">⌾<span>87% FIT</span></div><div class="match-box"><small>ANONYMOUS MANDATE</small><b>Core / Core+</b><p>Spain · €30–60M · urban only</p></div></div>`
];


const STATIC_UI = {
  en: {
    crumbs:'Assets <i>›</i> Hotel / urban <i>›</i> Teaser',
    confidential:'CONFIDENTIAL', teaserMeta:'INSTITUTIONAL TEASER<br>JUN 2026', teaserTitle:'Urban hotel<br><em>prime location</em>', location:'Barcelona · Spain', image:'ANONYMOUS ASSET IMAGE', sheetStats:['GLA','keys','category'], sheetFooter:'Source-controlled · 1 / 3', sidebar:['Summary','Documents','Provenance','Matches','Activity'], tabs:['Provenance','Key data','Notes'], mandate:'Spain <i>·</i> €50m–€150m <i>·</i> 87% match', portfolioLabels:['Assets in portfolio','Average coverage','Total volume','Yield range','Teasers issued','Assets in Dark Pool','Active mandates','New matches'], portfolioStatus:['+3 this month','+8% vs. last review','12 active dossiers','Documented range','04 this month','Anonymous','03 new matches','Last 30 days'], pricingFeatures:[['1 user seat','Up to 3 simultaneous assets','3 assets with active Dark Pool matching','Unlimited A4 teasers','Basic provenance and conflict audit'],['Up to 3 users','Up to 15 simultaneous assets','All assets in Dark Pool','3 acquisition mandates on radar','Brand and co-brokerage protocol'],['Up to 10 users','Up to 30 simultaneous assets','All assets in Dark Pool','Unlimited acquisition mandates','Priority institutional support']], footerLinks:['How it works','Pricing','FAQ','Access platform ↗'], demo:{files:['PDF','XLS','TXT'],reading:'24 pages · 6.4 MB · reading in browser',sheets:'12 sheets · 1.2 MB',note:'3.1 KB · pasted note',drop:'Drop more evidence',formats:'PDF · XLSX · DOCX · notes',source1:'ASSET INFORMATION.PDF',source2:'OPERATING_MODEL.XLSX',verified:'VERIFIED',price:'ASKING PRICE',yield:'STABILIZED YIELD',cite:'Each figure retains its source reference: <b>PDF · p. 03 · paragraph 4</b> and <b>XLSX · sheet Returns · cell D8</b>.',conflict:'DOCUMENT CONFLICT · HOTEL_KEYS',underReview:'UNDER REVIEW',sourceA:'Asset information.pdf',sourceB:'Broker notes.txt',pageA:'Page 7',pageB:'Note 02',output:'Output status',notPrinted:'Not printed',levels:['LEVEL 01','LEVEL 02','LEVEL 03'],visibility:['Text only','One photo','Gallery'],visibilityBody:['Financial ratios and technical narrative. Most restrictive and confidential.','One anonymous image or audited architectural plan.','Multiple images without brands or urban landmarks.'],a4Meta:'A4 TEASER',a4Title:'Urban hotel<br><em>prime location</em>',ready:'READY TO SHARE',readyBody:'Every printed datum has a source. Every hidden datum stays hidden.',asset:'ANONYMOUS ASSET',mandate:'ANONYMOUS MANDATE',fit:'87% FIT'}
  },
  es: {
    crumbs:'Activos <i>›</i> Hotel / urbano <i>›</i> Teaser',
    confidential:'CONFIDENCIAL', teaserMeta:'TEASER INSTITUCIONAL<br>JUN 2026', teaserTitle:'Hotel urbano<br><em>ubicación prime</em>', location:'Barcelona · España', image:'IMAGEN ANÓNIMA DEL ACTIVO', sheetStats:['GLA','habitaciones','categoría'], sheetFooter:'Trazable por origen · 1 / 3', sidebar:['Resumen','Documentos','Procedencia','Cruces','Actividad'], tabs:['Procedencia','Datos clave','Notas'], mandate:'España <i>·</i> €50M–€150M <i>·</i> 87% encaje', portfolioLabels:['Activos en cartera','Cobertura media','Volumen total','Rango de yield','Teasers emitidos','Activos en Dark Pool','Mandatos activos','Cruces nuevos'], portfolioStatus:['+3 este mes','+8% vs. última revisión','12 expedientes activos','Rango documentado','04 este mes','Anónimo','03 cruces nuevos','Últimos 30 días'], pricingFeatures:[['1 plaza de usuario','Hasta 3 activos simultáneos','3 activos con matching Dark Pool activo','Teasers A4 ilimitados','Procedencia y auditoría básica'],['Hasta 3 usuarios','Hasta 15 activos simultáneos','Todos los activos en Dark Pool','3 mandatos de compra en el radar','Marca y protocolo de co-brokerage'],['Hasta 10 usuarios','Hasta 30 activos simultáneos','Todos los activos en Dark Pool','Mandatos de compra ilimitados','Soporte institucional prioritario']], footerLinks:['Cómo funciona','Precios','FAQ','Acceder a la plataforma ↗'], demo:{files:['PDF','XLS','TXT'],reading:'24 páginas · 6,4 MB · lectura en navegador',sheets:'12 hojas · 1,2 MB',note:'3,1 KB · nota pegada',drop:'Añadir más evidencia',formats:'PDF · XLSX · DOCX · notas',source1:'INFORMACIÓN_ACTIVO.PDF',source2:'MODELO_OPERATIVO.XLSX',verified:'VERIFICADO',price:'PRECIO DE SALIDA',yield:'YIELD ESTABILIZADO',cite:'Cada cifra conserva su referencia: <b>PDF · pág. 03 · párrafo 4</b> y <b>XLSX · hoja Returns · celda D8</b>.',conflict:'CONFLICTO DOCUMENTAL · HOTEL_KEYS',underReview:'EN VERIFICACIÓN',sourceA:'Información del activo.pdf',sourceB:'Nota del broker.txt',pageA:'Página 7',pageB:'Nota 02',output:'Estado de salida',notPrinted:'No se imprime',levels:['NIVEL 01','NIVEL 02','NIVEL 03'],visibility:['Solo texto','Una foto','Galería'],visibilityBody:['Ratios financieros y narrativa técnica. El nivel más restrictivo y confidencial.','Una imagen anónima o un plano arquitectónico auditado.','Varias imágenes sin marcas ni hitos urbanos.'],a4Meta:'TEASER A4',a4Title:'Hotel urbano<br><em>ubicación prime</em>',ready:'LISTO PARA COMPARTIR',readyBody:'Cada dato impreso tiene una fuente. Cada dato oculto permanece oculto.',asset:'ACTIVO ANÓNIMO',mandate:'MANDATO ANÓNIMO',fit:'87% ENCAJE'}
  },
  fr: {
    crumbs:'Actifs <i>›</i> Hôtel / urbain <i>›</i> Teaser',
    confidential:'CONFIDENTIEL', teaserMeta:'TEASER INSTITUTIONNEL<br>JUIN 2026', teaserTitle:'Hôtel urbain<br><em>emplacement prime</em>', location:'Barcelone · Espagne', image:'IMAGE ANONYME DE L’ACTIF', sheetStats:['GLA','chambres','catégorie'], sheetFooter:'Traçable par source · 1 / 3', sidebar:['Résumé','Documents','Provenance','Matchings','Activité'], tabs:['Provenance','Données clés','Notes'], mandate:'Espagne <i>·</i> €50M–€150M <i>·</i> adéquation 87%', portfolioLabels:['Actifs en portefeuille','Couverture moyenne','Volume total','Fourchette de yield','Teasers émis','Actifs dans le Dark Pool','Mandats actifs','Nouveaux matchings'], portfolioStatus:['+3 ce mois-ci','+8% vs. dernière revue','12 dossiers actifs','Fourchette documentée','04 ce mois-ci','Anonyme','03 nouvelles adéquations','30 derniers jours'], pricingFeatures:[['1 siège utilisateur','Jusqu’à 3 actifs simultanés','3 actifs avec matching Dark Pool actif','Teasers A4 illimités','Provenance et audit de conflits de base'],['Jusqu’à 3 utilisateurs','Jusqu’à 15 actifs simultanés','Tous les actifs dans le Dark Pool','3 mandats d’acquisition dans le radar','Marque et protocole de co-courtage'],['Jusqu’à 10 utilisateurs','Jusqu’à 30 actifs simultanés','Tous les actifs dans le Dark Pool','Mandats d’acquisition illimités','Support institutionnel prioritaire']], footerLinks:['Comment ça marche','Tarifs','FAQ','Accéder à la plateforme ↗'], demo:{files:['PDF','XLS','TXT'],reading:'24 pages · 6,4 Mo · lecture dans le navigateur',sheets:'12 feuilles · 1,2 Mo',note:'3,1 Ko · note collée',drop:'Ajouter des preuves',formats:'PDF · XLSX · DOCX · notes',source1:'INFORMATIONS_ACTIF.PDF',source2:'MODÈLE_OPÉRATIONNEL.XLSX',verified:'VÉRIFIÉ',price:'PRIX DEMANDÉ',yield:'YIELD STABILISÉ',cite:'Chaque chiffre conserve sa référence : <b>PDF · p. 03 · paragraphe 4</b> et <b>XLSX · feuille Returns · cellule D8</b>.',conflict:'CONFLIT DOCUMENTAIRE · HOTEL_KEYS',underReview:'À VÉRIFIER',sourceA:'Informations actif.pdf',sourceB:'Note du broker.txt',pageA:'Page 7',pageB:'Note 02',output:'État de sortie',notPrinted:'Non imprimé',levels:['NIVEAU 01','NIVEAU 02','NIVEAU 03'],visibility:['Texte seul','Une photo','Galerie'],visibilityBody:['Ratios financiers et récit technique. Le niveau le plus restrictif et confidentiel.','Une image anonyme ou un plan architectural audité.','Plusieurs images sans marques ni repères urbains.'],a4Meta:'TEASER A4',a4Title:'Hôtel urbain<br><em>emplacement prime</em>',ready:'PRÊT À PARTAGER',readyBody:'Chaque donnée imprimée a une source. Chaque donnée masquée reste masquée.',asset:'ACTIF ANONYME',mandate:'MANDAT ANONYME',fit:'87% ADÉQUATION'}
  }
};

function setText(selector, value, html = false) { const el = $(selector); if (el) html ? (el.innerHTML = value) : (el.textContent = value); }
function setAll(selector, values, html = false) { $$(selector).forEach((el, i) => { if (values[i] !== undefined) html ? (el.innerHTML = values[i]) : (el.textContent = values[i]); }); }
function localizeStaticUi() {
  const ui = STATIC_UI[currentLang];
  setText('.crumbs', ui.crumbs, true); setAll('.app-sidebar .side-item', ui.sidebar); setAll('.panel-tabs span', ui.tabs);
  setAll('.teaser-sheet .sheet-meta span', [ui.confidential, ui.teaserMeta], true); setText('.teaser-sheet h3', ui.teaserTitle, true); setText('.sheet-location', ui.location); setText('.sheet-image span', ui.image); setAll('.sheet-stats small', ui.sheetStats); setText('.sheet-footer span', ui.sheetFooter);
  setText('.mandate-card p', ui.mandate, true); setAll('.metric-grid small', ui.portfolioLabels); setAll('.metric-grid .metric-up,.metric-grid .metric-neutral', ui.portfolioStatus);
  $$('.price-card ul').forEach((list, i) => { list.innerHTML = ui.pricingFeatures[i].map((item) => `<li>${item}</li>`).join(''); });
  setAll('.footer-links a', ui.footerLinks, true);
  localizeDemoStage();
}
function localizeDemoStage() {
  const d = STATIC_UI[currentLang].demo;
  if (currentStep === 0) { setText('.demo-file.is-uploading b','asset_information.pdf'); setText('.demo-file.is-uploading small',d.reading); setText('.demo-file:nth-child(2) b','operating_model.xlsx'); setText('.demo-file:nth-child(2) small',d.sheets); setText('.demo-file:nth-child(3) b','broker_notes.txt'); setText('.demo-file:nth-child(3) small',d.note); setText('.demo-upload b',d.drop); setText('.demo-upload small',d.formats); }
  if (currentStep === 1) { setText('.proof-source-card:nth-child(1) label span',d.source1); setText('.proof-source-card:nth-child(2) label span',d.source2); setAll('.proof-source-card label b',[d.verified,d.verified]); setText('.proof-source-card:nth-child(1) .proof-data small',d.price); setText('.proof-source-card:nth-child(2) .proof-data small',d.yield); setText('.proof-cite span:last-child',d.cite,true); }
  if (currentStep === 2) { setText('.conflict-head span:first-child',d.conflict); setText('.conflict-head span:last-child',d.underReview); setAll('.conflict-row span',[d.sourceA,d.sourceB,d.output]); setAll('.conflict-row em',[d.pageA,d.pageB,d.notPrinted]); }
  if (currentStep === 3) { setAll('.visibility-card span',d.levels); setAll('.visibility-card h4',d.visibility); setAll('.visibility-card p',d.visibilityBody); }
  if (currentStep === 4) { setText('.a4-sheet .sheet-meta span:last-child',d.a4Meta); setText('.a4-sheet h4',d.a4Title,true); setText('.a4-side b',d.ready); setText('.a4-side span',d.readyBody); }
  if (currentStep === 5) { setText('.match-box:nth-child(1) small',d.asset); setText('.match-box:nth-child(2) small',d.mandate); setText('.match-mid span',d.fit); }
}

let currentLang = 'en';
let currentStep = 0;
let billing = 'monthly';
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const get = (path) => path.split('.').reduce((obj, key) => obj?.[key], I18N[currentLang]);

function applyTranslations() {
  const locale = I18N[currentLang];
  document.documentElement.lang = currentLang;
  $$('[data-i18n]').forEach((el) => {
    const value = get(el.dataset.i18n);
    if (value !== undefined) el.innerHTML = value;
  });
  const navMap = { 'a[href="#how-it-works"]':'nav.how', 'a[href="#sell-side"]':'nav.sell', 'a[href="#buy-side"]':'nav.buy', 'a[href="#pricing"]':'nav.pricing', '.button-small':'nav.access' };
  Object.entries(navMap).forEach(([selector, path]) => { const el = $(selector); if (el) el.innerHTML = get(path); });
  $$('.step-button').forEach((button, index) => {
    button.querySelector('[data-step-title]').textContent = locale.steps[index].title;
    button.querySelector('[data-step-short]').textContent = locale.steps[index].short;
  });
  renderWalkthrough();
  renderFaq();
  $$('.billing-btn').forEach((button) => { button.textContent = button.dataset.billing === 'monthly' ? (currentLang === 'fr' ? 'Mensuel' : currentLang === 'es' ? 'Mensual' : 'Monthly') : (currentLang === 'fr' ? 'Annuel' : currentLang === 'es' ? 'Anual' : 'Annual −20%'); });
  updatePriceCopy();
  localizeStaticUi();
}

function renderWalkthrough() {
  const locale = I18N[currentLang];
  $('#stage-content').innerHTML = demoTemplates[currentStep];
  localizeDemoStage();
  $('#step-name').textContent = locale.steps[currentStep].title;
  $('#stage-description').textContent = locale.steps[currentStep].description;
  $('#step-current').textContent = String(currentStep + 1).padStart(2, '0');
  $$('.step-button').forEach((button, index) => { const active = index === currentStep; button.classList.toggle('is-active', active); button.setAttribute('aria-selected', String(active)); });
  const prev = $('#step-prev'); const next = $('#step-next');
  prev.disabled = currentStep === 0; next.disabled = currentStep === locale.steps.length - 1;
  prev.style.opacity = prev.disabled ? '.35' : '1'; next.style.opacity = next.disabled ? '.35' : '1';
}

function renderFaq() {
  const list = $('#faq-list');
  list.innerHTML = I18N[currentLang].faqItems.map(([question, answer], index) => `<div class="faq-item${index === 0 ? ' is-open' : ''}"><button class="faq-question" type="button" aria-expanded="${index === 0}"><span>${question}</span><span aria-hidden="true">+</span></button><div class="faq-answer"><div>${answer}</div></div></div>`).join('');
  $$('.faq-question', list).forEach((button) => button.addEventListener('click', () => { const item = button.parentElement; const open = item.classList.toggle('is-open'); button.setAttribute('aria-expanded', String(open)); }));
}

function updatePriceCopy() { $$('.price-cta').forEach((el, index) => { const copy = index === 0 ? (currentLang === 'es' ? 'Elegir Solo' : currentLang === 'fr' ? 'Choisir Solo' : 'Choose Solo') : index === 1 ? (currentLang === 'es' ? 'Elegir Boutique' : currentLang === 'fr' ? 'Choisir Boutique' : 'Choose Boutique') : (currentLang === 'es' ? 'Hablar con nosotros' : currentLang === 'fr' ? 'Parler avec nous' : 'Talk to us'); el.innerHTML = `${copy} <span>↗</span>`; }); }

function setLanguage(lang) { if (!I18N[lang]) return; currentLang = lang; $$('.lang-btn').forEach((button) => button.classList.toggle('is-active', button.dataset.lang === lang)); applyTranslations(); try { localStorage.setItem('loptor-lang', lang); } catch (_) {} }

function setBilling(nextBilling) { billing = nextBilling; $$('.billing-btn').forEach((button) => button.classList.toggle('is-active', button.dataset.billing === nextBilling)); const prices = nextBilling === 'annual' ? ['€55','€159','€390'] : ['€69','€199','€390']; $$('.monthly-price').forEach((el, index) => { el.textContent = prices[index]; }); $$('.annual-copy').forEach((el, index) => { el.textContent = nextBilling === 'annual' ? (index === 2 ? '€4,680 / year · annual only' : 'Annual billing · save 20%') : (index === 2 ? '€4,680 / year · annual only' : index === 0 ? '€55 / month billed annually' : '€159 / month billed annually'); }); }

function wireEvents() {
  $$('.lang-btn').forEach((button) => button.addEventListener('click', () => setLanguage(button.dataset.lang)));
  $$('.step-button').forEach((button) => button.addEventListener('click', () => { currentStep = Number(button.dataset.step); renderWalkthrough(); }));
  $('#step-prev').addEventListener('click', () => { if (currentStep > 0) { currentStep -= 1; renderWalkthrough(); } });
  $('#step-next').addEventListener('click', () => { if (currentStep < 5) { currentStep += 1; renderWalkthrough(); } });
  $$('.billing-btn').forEach((button) => button.addEventListener('click', () => setBilling(button.dataset.billing)));
  const menu = $('.mobile-menu'); const nav = $('.main-nav');
  menu.addEventListener('click', () => { const open = nav.classList.toggle('is-open'); menu.setAttribute('aria-expanded', String(open)); });
  $$('.main-nav a').forEach((link) => link.addEventListener('click', () => { nav.classList.remove('is-open'); menu.setAttribute('aria-expanded','false'); }));
}

try { const saved = localStorage.getItem('loptor-lang'); if (saved && I18N[saved]) currentLang = saved; } catch (_) {}
wireEvents();
$$('.lang-btn').forEach((button) => button.classList.toggle('is-active', button.dataset.lang === currentLang));
applyTranslations();
